name: RPM Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - registry.fedoraproject.org/fedora:rawhide
          - registry.fedoraproject.org/fedora:latest
    container:
      image: ${{ matrix.container }}
    steps:

    - name: Install rpmlint
      run: |
        sudo dnf -y install rpmlint

    - uses: actions/checkout@v4

    - name: rpmlint
      run: |
        rpmlint --verbose fedora-minimal.spec
