name: RPM Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:

    - name: Install rpmlint
      run: |
        sudo dnf -y install rpmlint

    - uses: actions/checkout@v2

    - name: rpmlint
      run: |
        rpmlint --verbose fedora-minimal.spec
